export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS'
export const RECEIVE_ORDER = 'RECEIVE_ORDER'

export const CHANGE_QUANTITY = 'CHANGE_QUANTITY'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'

export const CHECKOUT_REQUEST = 'CHECKOUT_REQUEST'
export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS'
export const CHECKOUT_FAILURE = 'CHECKOUT_FAILURE'
